### PR TITLE
created getOidTokenElements function

### PR DESCRIPTION
**Pull request by shawnmarie**
Found an error with the getAssetType function, created an invalid Url when called in the executeOperation function.  Suggest replace getAssetType function with new getOidTokenElements. This function allows for distinct selection of the Asset Type and Oid values of the OidToken.

### CODE REVIEW

**Comment by andrew-codes** [comment]
The data being returned is really the internals of an Oid and is being created from an OidToken. I feel that maybe the Oid concept should be a first class citizen in the SDK and not just an utility function. It could be capable of returning the AssetType, Number, and Token; as well as convert from a token back to an Oid. What do you think, @shawnmarie and @JogoShugh ?

Also, are the specs updated or do they need to be for this PR's changes?

**Comment by shawnmarie** [comment]
I agree with you @andrew-codes. Interested to see your improvements!
Sorry, I neglected to update the specs!  My bad.

**Comment by andrew-codes** [comment]
No worries. We can pair on it if you like or I can cook something up and see what it turns out to be like. Either is fine with me.

**Comment by shawnmarie** [comment]
Not urgent. Would love to pair on it.

**Comment by andrew-codes** [comment]
Sorry, didn't see your message until it was too late. Let's pair on the changes I made sometime today, then we can merge them in if they look good.

**Pull request merged**
